INSERT INTO infobox_configuration VALUES('#tID#', '', 'categories.php', 'BOX_HEADING_CATEGORIES', 'no', 'left', '1', now(), now(), 'Categories', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'categories1.php', 'BOX_HEADING_CATEGORIES1', 'no', 'left', '2', now(), now(), 'Categories', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'categories2.php', 'BOX_HEADING_CATEGORIES2', 'no', 'left', '3', now(), now(), 'Categories', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'categories3.php', 'BOX_HEADING_CATEGORIES3', 'no', 'left', '4', now(), now(), 'Categories', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'categories4.php', 'BOX_HEADING_CATEGORIES4', 'yes', 'left', '5', now(), now(), 'Categories', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'theme_select.php', 'BOX_HEADING_TEMPLATE_SELECT', 'no', 'left', '6', now(), now(), 'Select Template', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'reviews.php', 'BOX_HEADING_REVIEWS', 'no', 'left', '7', now(), now(), 'Reviews', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'specials.php', 'BOX_HEADING_SPECIALS', 'no', 'left', '8', now(), now(), 'Specials', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'faqdesk_latest.php', 'BOX_HEADING_FAQDESK_LATEST', 'no', 'left', '9', now(), now(), 'FaqDesk Latest', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'faqdesk.php', 'BOX_HEADING_FAQDESK_CATEGORIES', 'no', 'left', '10', now(), now(), 'FaqDesk', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'newsdesk_latest.php', 'BOX_HEADING_NEWSDESK_LATEST', 'no', 'left', '11', now(), now(), 'NewsDesk Latest', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'newsdesk.php', 'BOX_HEADING_NEWSDESK_CATEGORIES', 'no', 'left', '12', now(), now(), 'NewsDesk', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'search.php', 'BOX_HEADING_SEARCH', 'no', 'left', '13', now(), now(), 'Quick Find', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'manufacturers.php', 'BOX_HEADING_MANUFACTURERS', 'no', 'left', '14', now(), now(), 'Manufactures', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'manufacturer_info.php', 'BOX_HEADING_MANUFACTURER_INFO', 'no', 'left', '15', now(), now(), 'Manufactures Info', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'product_notifications.php', 'BOX_HEADING_NOTIFICATIONS', 'no', 'left', '16', now(), now(), 'Notifications', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'tell_a_friend.php', 'BOX_HEADING_TELL_A_FRIEND', 'no', 'left', '17', now(), now(), 'Tell A Friend', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'whats_new.php', 'BOX_HEADING_WHATS_NEW', 'no', 'left', '18', now(), now(), 'Latest products', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'shop_by_price.php', 'BOX_HEADING_SHOP_BY_PRICE', 'no', 'left', '19', now(), now(), 'Shop by Price', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'featured.php', 'BOX_HEADING_FEATURED', 'no', 'left', '20', now(), now(), 'Featured', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'affiliate.php', 'BOX_HEADING_AFFILIATE', 'no', 'left', '21', now(), now(), 'Affiliate Info', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'links.php', 'BOX_HEADING_LINKS', 'no', 'left', '22', now(), now(), 'Links', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'whos_online.php', 'BOX_HEADING_WHOS_ONLINE', 'no', 'left', '22', now(), now(), 'Who\'\s Online', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'googlead.php', 'BOX_GOOGLE_AD_BANNER_HEADING', 'no', 'left', '23', now(), now(), 'Google Ad', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'shopping_cart.php', 'BOX_HEADING_SHOPPING_CART', 'no', 'right', '1', now(), now(), 'Shopping Cart', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'customer_gv.php', 'BOX_HEADING_GIFT_VOUCHER', 'no', 'right', '2', now(), now(), 'Gift Voucher', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'loginbox.php', 'BOX_HEADING_LOGIN', 'no', 'right', '3', now(), now(), 'Your Account', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'best_sellers.php', 'BOX_HEADING_BESTSELLERS', 'no', 'right', 4, now(), now(), 'Best Sellers', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'order_history.php', 'BOX_HEADING_CUSTOMER_ORDERS', 'no', 'right', '5', now(), now(), 'Order History', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'languages.php', 'BOX_HEADING_LANGUAGES', 'no', 'right', '6', now(), now(), 'Languages', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'currencies.php', 'BOX_HEADING_CURRENCIES', 'no', 'right', '7', now(), now(), 'Currencies', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'information_table.php', 'BOX_HEADING_INFORMATION_TABLE', 'yes', 'left', '8', '2004-04-17 10:06:01', now(), 'Information', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'downloads.php', 'BOX_HEADING_DOWNLOADS', 'no', 'right', '10', now(), now(), 'You Have a Download', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'donate.php', 'BOX_HEADING_DONATE', 'no', 'right', '11', now(), now(), 'Donate', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'card1.php', 'BOX_HEADING_CARD1', 'no', 'right', '12', now(), now(), 'Cards We Accept', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'search1.php', 'BOX_HEADING_SEARCH1', 'yes', 'left', '13', now(), now(), 'Advance Search', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'wishlist.php', 'BOX_HEADING_WISHLIST', 'no', 'right', '14', now(), now(), 'Wishlist', 'infobox', '#989899');
INSERT INTO infobox_configuration VALUES('#tID#', '', 'boxad.php', 'BOX_AD_BANNER_HEADING', 'no', 'right', '15', now(), now(), 'Advertise', 'infobox', '#989899');
UPDATE template SET date_added= now(), last_modified= now(), template_image= "Original.gif", template_cellpadding_main ="0", template_cellpadding_sub= "0", template_cellpadding_left= "2", template_cellpadding_right= "3", site_width= "736", include_column_left= "yes", include_column_right= "no", box_width_left= "130", box_width_right= "200", main_table_border= "no", active= "1", languages_in_header= "no", cart_in_header= "no", show_header_link_buttons="yes", module_one= "mainpage.php", module_two= "", module_three= "", module_four= "", module_five= "", module_six= "", customer_greeting= "no", side_box_left_width= "11", side_box_right_width= "11"  WHERE template_id="#tID#"